# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e981f436dcf91706fe3afc060f72f1a3d1f2e4f0f852768e7a29feecd8ffe99626d41b4472d1bc9dcd9f100b771a75e30bec3983fbe3458c7918dff6d763dea

test:
  secret_key_base: ced973bc98658b55dd3fc429d5f093e6c3877ade2b8173e0eb0a55477535fe710b2636eef77d6ab26f42a0ba2f77f1b472188d3a9f9b7e6f8d1a98e3723e63f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
